### ISSUE TITLE
webpack loader

### ISSUE THREAD

**Issue by bvoelker** [niksy/get-sass-vars#1]
Any chance you could make a webpack loader out of this? So front end developers could easily get sass variables?

Thanks

**Comment by niksy** [comment]
@bvoelker did you manage to make loader for this?

**Comment by bvoelker** [comment]
I sure did. :)

https://github.com/brianvoe/get-sass-vars-loader

**Comment by bvoelker** [comment]
Your package saved my ass!

**Comment by niksy** [comment]
@bvoelker Nice, glad I could be of help :) I see that you’re only using string argument, have you considered adding options argument?

Also, I will add your package as related project to README so other people can benefit from it.

**Comment by bvoelker** [comment]
Hey i wanted to ask you something. So if your using sass you probably have @import paths to import other sass files. Does it traverse those files and get the variables from them as well?

**Comment by niksy** [comment]
No, only file which you explictly requested.
