### ISSUE TITLE
adding sassOptions with includePaths not working

### ISSUE THREAD

**Issue by venkatesh-nagineni** [niksy/get-sass-vars#12]
I have sass file variables depend on another sass file to import but currently giving an error Can't find stylesheet to import

i have tried different ways to add includePaths to work like this

`const variables = await sassVars(fileContent, {sassOptions: {includePaths: [path.resolve(inputDirPath)]}});`

here it is sass file i have

```
_radius.scss

@import 'sizes';

$dsRadiusNoradius: $dsZeroGridSize;
```

repro link https://github.com/venkatesh-nagineni/scss_vars

does anyone have clue how does this work

**Comment by niksy** [comment]
Can you provide reproduction repository?

**Comment by venkatesh-nagineni** [comment]
hi, thx for the quick reply, here is repro link, just run npm run build then error will popup with can't find stylesheet

https://github.com/venkatesh-nagineni/scss_vars

**Comment by niksy** [comment]
Oh, I see, documentation points to wrong URL. As of https://github.com/niksy/get-sass-vars/releases/tag/v4.0.0, this module uses new Sass API which has `loadPaths` instead of `includePaths`.

I will update the documentation.

**Comment by venkatesh-nagineni** [comment]
working great, thank you
