### ISSUE TITLE
Tests break when updating `node-sass` to the latest version (4.5.0)

### ISSUE THREAD

**Issue by lsavage92** [niksy/get-sass-vars#2]
` ERROR in ./~/get-sass-vars-loader!./~/dh2o-atlantis/src/scss/misc/_colors.scss
       Module build failed: Error: ENOENT: no such file or directory, scandir '/tmp/build_3661ab6abd110b0d4196a082a8747220/DigitalH2O-dh2o-salacia-1d1d3df80c99b2da91dcb1486c3408c13aa3b3f6/node_modules/get-sass-vars/node_modules/node-sass/vendor'`

We got this error in our production application and I went to attempt to clone this repo and bump the `node-sass` dependency but it broke all the tests. For now we are going to manage our versions better in order to alleviate this, but just wanted to let you know.

**Comment by brianvoe** [comment]
Any way you get get-sass-vars compatible with node-sass ^4.5.0?

**Comment by niksy** [comment]
@lsavage92 @brianvoe I’ve pushed new release which supports latest node-sass and node-sass-json-functions and it should work now. Can you please confirm?

**Comment by niksy** [comment]
@lsavage92 @brianvoe Is this still actual for you?

**Comment by brianvoe** [comment]
I cant say that I even use this anymore

**Comment by lsavage92** [comment]
I also do not use this anymore either, sorry!
