### ISSUE TITLE
error in types definitions

### ISSUE THREAD

**Issue by jovpet** [niksy/get-sass-vars#4]
Once the project is built, in `esm/index.d.ts` types are wrong. Here is the current output:

```ts
export namespace _sass {
    type Options = import('sass').Options;
}
export type Options = {
    /**
     * Camelize first-level JSON object keys and strip inital `$` (e.g. `$foo-bar` will become `fooBar`).
     */
    camelize?: boolean | undefined;
    /**
     * Options for Sass renderer.
     */
    sassOptions?: sass.Options | undefined;
};
```

please note that `sassOptions?: sass.Options | undefined;` should be `sassOptions?: _sass.Options | undefined;`

**Comment by niksy** [comment]
@jovpet thanks for noticing it! It’s related to how TypeScript parses optional parameters in brackets in JSDoc. I’ve switched to syntax which is better supported. I’ve published patched version.
