### ISSUE TITLE
HOT: All nemeric values got rounded (no-way to prevent this)

### ISSUE THREAD

**Issue by 7iomka** [niksy/get-sass-vars#5]
Input
```scss
$grault: 1.23456789px, 1.23456789;
```

Output
```
"$grault":["1px",1]
```

Node v16.5.0
sass 1.45.1

Need help!

**Comment by 7iomka** [comment]
Seems something with dependency `node-sass-json-functions`

I put console.log inside `getJsonValueFromSassValue` method and issue there:
```
{
  value: sass.types.Number { dartValue: 0.1875rem },
  resolvedValue: '0rem'
}
```

**Comment by 7iomka** [comment]
https://github.com/niksy/node-sass-json-functions/blob/63d1da01e2d41aa162a294d9337c900c327b1732/lib/sass-to-json.js#L34

Seems this issue happened after creator hardcoded precision value instead of get it from config
https://github.com/niksy/node-sass-json-functions/blob/63d1da01e2d41aa162a294d9337c900c327b1732/lib/sass-to-json.js#L34

I created issue
https://github.com/niksy/node-sass-json-functions/issues/6

**Comment by 7iomka** [comment]
@niksy Hi
Should I wait for a quick solution to the problem or should I create a fork and temporarily fix it myself?
Thanks!

**Comment by niksy** [comment]
I’ll push new version soon.

**Comment by niksy** [comment]
@7iomka done!
