### ISSUE TITLE
Parsing lines with calc()

### ISSUE THREAD

**Issue by mgrycz** [niksy/get-sass-vars#8]
I want to parse a source file that has a line with `calc()` as its value.

After returning a JSON content, that specific line is `null`.

How should I use the library so that lines with `calc()` are left as they are in the output?

**Comment by niksy** [comment]
Thank you for reporting this! This is actually related to parsing support in [dependancy](https://github.com/niksy/node-sass-json-functions/issues/7).

**Comment by niksy** [comment]
Added support in https://github.com/niksy/node-sass-json-functions/releases/tag/v4.1.0

Reinstall get-sass-vars and new version of node-sass-json-functions will be pulled.
