### ISSUE TITLE
Can't distinguish comma and space separated lists

### ISSUE THREAD

**Issue by esturcke** [niksy/get-sass-vars#9]
The following:

```js
import sassVars from 'get-sass-vars';

(async () => {
  console.log(await sassVars(`
    $comma: 1, 2, 3;   
    $space: 1 2 3;
    $mixed: 1, 2 3;
    $quote: 1, "2 3";
  `));
})();
```

results in:

```
{
  '$comma': [ 1, 2, 3 ],
  '$space': [ 1, 2, 3 ],
  '$mixed': [ 1, [ 2, 3 ] ],
  '$quote': [ 1, '2 3' ]
}
```

`$comma` and `$space` are not reversible. I don't see a way around this giving the simple output data model. Perhaps this can be at least documented as expected behavior?

**Comment by niksy** [comment]
What do you mean they’re not reversible?

**Comment by esturcke** [comment]
Hi @niksy, I mean that we lose information about the separator when extracting variable. If I have an extracted variable with value `[1, 2, 3]`, I don't know if it was originally `1, 2, 3` or `1 2 3`.

In my case I'm using the extracted variables from a design system and making some local overrides with `emotion`. I'm converting arrays like this back to strings to do that. There are only 4 variables that are using commas, so not a big deal to handle as special cases.

Overall `get-sass-vars` is working great and it was very easy to use. Thanks!

**Comment by niksy** [comment]
@esturcke this is what we get when using Sass API and you can see the implementation here: https://github.com/niksy/node-sass-json-functions/blob/master/lib/sass-to-json.js

I think this can be seen as sort of an edge case, so it’s best to keep it consistent. Using commas and spaces as delimiters for arrays is valid in Sass, so I think what we currently do is best of both worlds.

**Comment by esturcke** [comment]
Yeah, makes sense to keep it as is. I have an easy workaround for my case.
